import { PHOTO } from "./images";
import type { Category, Product, Review } from "./types";

export const MODELS = ["L6", "L7", "L8", "L9", "MEGA"] as const;

export const CATALOG_CATEGORIES: Category[] = [
  { id: "all", name: "Все товары", description: "Весь ассортимент KIBER SMART AUTO", image: PHOTO.interior, count: 124 },
  { id: "salon", name: "Салон", description: "Коврики, чехлы, органайзеры", image: PHOTO.interior, count: 28 },
  { id: "exterior", name: "Экстерьер", description: "Брызговики, защита, накладки", image: PHOTO.exteriorWheel, count: 24 },
  { id: "electronics", name: "Электроника", description: "Зарядки, компоненты, держатели", image: PHOTO.charger, count: 18 },
  { id: "comfort", name: "Комфорт", description: "Автохолодильники, органайзеры, аксессуары", image: PHOTO.cooler, count: 16 },
  { id: "protection", name: "Защита", description: "Пороги, накладки, плёнки", image: PHOTO.sillGuard, count: 12 },
  { id: "russification", name: "Русификация", description: "Язык, приложения, обновления", image: PHOTO.dashboardScreen, count: 8 },
  { id: "service", name: "Сервис", description: "Диагностика, ТО, ремонт", image: PHOTO.mechanic, count: 6 },
];

export const HOME_CATEGORIES: Category[] = [
  { id: "salon", name: "Салон", description: "Коврики, чехлы, органайзеры", image: PHOTO.interior, count: 28 },
  { id: "exterior", name: "Экстерьер", description: "Брызговики, защита, накладки", image: PHOTO.exteriorWheel, count: 24 },
  { id: "electronics", name: "Электроника", description: "Зарядки, компоненты, держатели", image: PHOTO.charger, count: 18 },
  { id: "russification", name: "Русификация", description: "Язык, приложения, обновления", image: PHOTO.dashboardScreen, count: 8 },
  { id: "service", name: "Сервис", description: "Диагностика, ТО, ремонт", image: PHOTO.mechanic, count: 6 },
];

const ALL_MODELS = [...MODELS];
const COLOR_SET = [
  { name: "Чёрный", hex: "#161616" },
  { name: "Серый", hex: "#6b6b6b" },
  { name: "Светло-серый", hex: "#b8b8b4" },
  { name: "Бежевый", hex: "#cdb794" },
];

const KEY_COLORS = [
  { name: "Оранжевый", hex: "#c8621a" },
  { name: "Белый", hex: "#e8e4dc" },
  { name: "Чёрный", hex: "#161616" },
  { name: "Коричневый", hex: "#8b6a4f" },
];
const PILLOW_COLORS = [
  { name: "Белый", hex: "#e8e4dc" },
  { name: "Чёрный", hex: "#161616" },
  { name: "Коричневый", hex: "#6b4226" },
  { name: "Оранжевый", hex: "#c8621a" },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "kovriki-v-salon-komplekt",
    name: "Коврики в салон (комплект)",
    categoryId: "salon",
    models: ALL_MODELS,
    price: 12500,
    rating: 4.9,
    reviewsCount: 124,
    inStock: true,
    image: PHOTO.mudMat,
    gallery: [PHOTO.mudMat, PHOTO.trunkMat, PHOTO.trunkMatAlt, PHOTO.interiorDetail],
    popularity: 100,
    colors: COLOR_SET,
    features: [
      "Идеальная посадка по форме пола",
      "Премиальный TPE материал",
      "Легкая очистка",
      "Не скользят",
      "Стильный дизайн с логотипом",
    ],
    compatibility: "L6 / L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Комплект ковриков в салон, изготовленных по 3D-слепку пола вашего Lixiang. Премиальный TPE-материал не скользит, не пахнет и легко моется — просто ополосните водой.",
  },
  {
    id: "p2",
    slug: "bryzgoviki-komplekt",
    name: "Брызговики",
    categoryId: "exterior",
    models: [],
    price: 2000,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 88,
    colors: [],
    features: [],
    compatibility: "",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Брызговики для автомобиля",
    photoFiles: { dir: "/images/products", names: ["brizgoviki"] },
  },
  {
    id: "p3",
    slug: "kovrik-v-bagazhnik",
    name: "Коврик в багажник",
    categoryId: "salon",
    models: ALL_MODELS,
    price: 9800,
    rating: 4.9,
    reviewsCount: 58,
    inStock: true,
    image: PHOTO.trunkMat,
    gallery: [PHOTO.trunkMat, PHOTO.trunkMatAlt, PHOTO.mudMat],
    popularity: 74,
    colors: [COLOR_SET[0], COLOR_SET[1]],
    features: [
      "Высокий борт против протекания",
      "Повторяет форму багажника",
      "Прочный TPE, не боится влаги",
      "Не скользит по кузову",
      "Логотип LIXIANG",
    ],
    compatibility: "L6 / L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Коврик с высоким бортом защищает багажник от грязи, воды и царапин — незаменим для поездок за город и перевозки крупных вещей.",
  },
  {
    id: "p4",
    slug: "avtokholodilnik-15l",
    name: "Автохолодильник 15 л",
    categoryId: "comfort",
    models: ALL_MODELS,
    price: 28000,
    rating: 4.7,
    reviewsCount: 34,
    inStock: true,
    image: PHOTO.cooler,
    gallery: [PHOTO.cooler, PHOTO.organizer],
    popularity: 61,
    colors: [COLOR_SET[0]],
    features: [
      "Компрессорное охлаждение до -20°C",
      "Питание от 12В и 220В",
      "Компактные размеры под багажник",
      "Тихая работа в дороге",
      "Крепление ремнями за подголовники",
    ],
    compatibility: "L6 / L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Компрессорный автохолодильник на 15 литров — держит еду и напитки холодными в любой поездке, подключается напрямую в разъём 12В.",
  },
  {
    id: "p5",
    slug: "organayzer-v-bagazhnik",
    name: "Органайзер в багажник",
    categoryId: "salon",
    models: ALL_MODELS,
    price: 2500,
    rating: 4.8,
    reviewsCount: 41,
    inStock: true,
    image: PHOTO.organizer,
    gallery: [PHOTO.organizer, PHOTO.trunkMat],
    popularity: 55,
    colors: [COLOR_SET[0], COLOR_SET[1]],
    features: [
      "Жёсткий каркас держит форму",
      "Разделители для порядка",
      "Складывается для хранения",
      "Нескользящее основание",
      "Ручки для переноски",
    ],
    compatibility: "L6 / L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Жёсткий органайзер с разделителями наводит порядок в багажнике и не даёт вещам кататься на поворотах.",
  },
  {
    id: "p6",
    slug: "besprovodnaya-zaryadka",
    name: "Беспроводная зарядка",
    categoryId: "electronics",
    models: ALL_MODELS,
    price: 12900,
    rating: 4.9,
    reviewsCount: 97,
    inStock: true,
    image: PHOTO.charger,
    gallery: [PHOTO.charger, PHOTO.dashboardScreen],
    popularity: 92,
    colors: [COLOR_SET[0]],
    features: [
      "Быстрая зарядка до 15 Вт",
      "Точная посадка в штатное место",
      "Не закрывает датчики и камеру",
      "Стабильная фиксация телефона",
      "Защита от перегрева",
    ],
    compatibility: "L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Беспроводная зарядка, повторяющая штатный дизайн консоли — быстрая зарядка на 15 Вт без проводов и лишних адаптеров.",
  },
  {
    id: "p7",
    slug: "porogi",
    name: "Пороги на Li L6 / L7 / L8 / L9 (без установки)",
    categoryId: "protection",
    models: ["L6", "L7", "L8", "L9"],
    price: 65000,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 80,
    colors: [],
    features: [],
    compatibility: "L6 / L7 / L8 / L9",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Пороги для автомобиля",
    photoFiles: { dir: "/images/products", names: ["porogi"] },
  },
  {
    id: "p8",
    slug: "aromatizator-li-auto",
    name: "Ароматизатор Li Auto",
    categoryId: "salon",
    models: ALL_MODELS,
    price: 4500,
    rating: 4.6,
    reviewsCount: 52,
    inStock: true,
    image: PHOTO.freshener,
    gallery: [PHOTO.freshener, PHOTO.interiorDetail],
    popularity: 40,
    colors: [COLOR_SET[0], COLOR_SET[2]],
    features: [
      "Фирменный дизайн LIXIANG",
      "Регулируемая интенсивность",
      "Долговечный сменный картридж",
      "Крепление в дефлектор",
      "Деликатный, не резкий аромат",
    ],
    compatibility: "L6 / L7 / L8 / L9 / MEGA",
    delivery: "Доставка от 1 до 3 дней",
    warranty: "Гарантия 12 месяцев",
    description:
      "Фирменный ароматизатор в салон с регулируемой интенсивностью аромата и сменным картриджем.",
  },
  {
    id: "p9",
    slug: "porogi-l6-s-ustanovkoy",
    name: "Пороги на Li L6 с установкой",
    categoryId: "protection",
    models: ["L6"],
    price: 70000,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 78,
    colors: [],
    features: [],
    compatibility: "L6",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Пороги для автомобиля",
    photoFiles: { dir: "/images/products", names: ["porogi"] },
  },
  {
    id: "p10",
    slug: "maslo-dvs",
    name: "Масла для ДВС",
    categoryId: "service",
    models: [],
    price: 2500,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 70,
    colors: [],
    features: [],
    compatibility: "",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Моторное масло для двигателя",
    photoFiles: { dir: "/images/products", names: ["maslo-dvs"] },
  },
  {
    id: "p11",
    slug: "chehol-dlya-klyucha",
    name: "Чехол для ключа",
    categoryId: "comfort",
    models: [],
    price: 500,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 76,
    colors: KEY_COLORS,
    features: [],
    compatibility: "",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Чехол для ключа автомобиля",
    photoFiles: { dir: "/images/keycases", names: ["1", "2", "3", "4", "5", "6", "7", "8"] },
  },
  {
    id: "p12",
    slug: "podushki-lixiang",
    name: "Подушки Lixiang",
    categoryId: "comfort",
    models: [],
    price: 1300,
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    image: "",
    gallery: [],
    popularity: 66,
    colors: PILLOW_COLORS,
    features: [],
    compatibility: "",
    delivery: "",
    warranty: "",
    description: "",
    alt: "Подушки Lixiang",
    photoFiles: { dir: "/images/products", names: ["podushki"] },
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    name: "Азизбек",
    model: "Lixiang L9",
    rating: 5,
    text: "Поставил коврики, русификацию и автохолодильник. Всё на высшем уровне! Отличный сервис, быстро, качественно.",
    avatarSeed: 12,
    photos: [PHOTO.mudMat, PHOTO.trunkMat],
  },
  {
    id: "r2",
    name: "Данияр",
    model: "Lixiang L7",
    rating: 5,
    text: "Профессиональная команда, оригинальные аксессуары, установили всё в срок. Рекомендую всем владельцам Lixiang.",
    avatarSeed: 33,
    photos: [PHOTO.wheelDetail, PHOTO.trunkMatAlt],
  },
];

export function findProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function categoryLabel(id: string) {
  return CATALOG_CATEGORIES.find((c) => c.id === id)?.name ?? id;
}
